on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    
      - name: Update pack formats
        id: update-formats
        uses: meza/action-minecraft-pack-versions@v1.0.24        
        with:
          output_path: 'formats.json'
          commit_enabled: true
          github_token: ${{ github.token }}
          cutoff_version: '1.21.1'
